import { MemeTemplate } from "./types";

const templates: MemeTemplate[] = [
  {
    id: "Gotcha",
    background: {
      src: "/memes/Gotcha.jpg",
      width: 528,
      height: 500,
      alt: "Gotcha",
    },
    textareas: [
      {
        id: "Me:",
        top: 280,
        left: 50,
        width: 200,
        height: 100,
        text: "ME",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Goal:",
        top: 80,
        left: 320,
        width: 200,
        height: 100,
        text: "Buy $BOT",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Me again:",
        top: 560,
        left: 180,
        width: 200,
        height: 100,
        text: "ME",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "The same goal:",
        top: 380,
        left: 410,
        width: 120,
        height: 200,
        text: "Buy $BOT",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Barrier:",
        top: 480,
        left: 10,
        width: 120,
        height: 200,
        text: "Bot snipers",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Gru",
    background: {
      src: "/memes/ThePlan.jpg",
      width: 528,
      height: 500,
      alt: "Gru",
    },
    textareas: [
      {
        id: "Idea:",
        top: 50,
        left: 150,
        width: 100,
        height: 100,
        text: "Create Meme Coin",
        size: 15,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Start:",
        top: 50,
        left: 415,
        width: 100,
        height: 100,
        text: "Create Twitter",
        size: 15,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Progress:",
        top: 220,
        left: 150,
        width: 100,
        height: 100,
        text: "We have an AI BOT",
        size: 15,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Fail:",
        top: 220,
        left: 420,
        width: 100,
        height: 100,
        text: "Failed ???",
        size: 15,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "We have exceeded the target:",
        top: 450,
        left: 310,
        width: 200,
        height: 200,
        text: "Pre-Sale sold out",
        size: 20,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Guy Looking",
    background: {
      src: "/memes/GuyLooking.jpg",
      width: 1600,
      height: 1066,
      alt: "Guy Looking",
    },
    textareas: [
      {
        id: "New:",
        top: 650,
        left: 50,
        width: 710,
        height: 320,
        text: "Bot",
        size: 70,
      },
      {
        id: "Person:",
        top: 500,
        left: 850,
        width: 400,
        height: 300,
        text: "My bag of ADAs",
        size: 80,
      },
      {
        id: "Old:",
        top: 550,
        left: 1250,
        width: 350,
        height: 320,
        text: "Cock",
        size: 70,
      },
    ],
  },
  {
    id: "Drake",
    background: {
      src: "/memes/Drake.jpg",
      width: 1200,
      height: 1200,
      alt: "Drake",
    },
    textareas: [
      {
        id: "Top:",
        top: 0,
        left: 600,
        width: 600,
        height: 600,
        text: "Top",
        size: 60,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Bottom:",
        top: 600,
        left: 600,
        width: 600,
        height: 600,
        text: "Bottom",
        size: 60,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Disaster Girl",
    background: {
      src: "/memes/DisasterGirl.jpg",
      width: 1200,
      height: 900,
      alt: "Disaster Girl",
    },
    textareas: [
      {
        id: "Tagline:",
        top: 750,
        left: 100,
        width: 900,
        height: 130,
        text: "Something Funny",
        size: 60,
      },
    ],
  },
  {
    id: "Cheating In School",
    background: {
      src: "/memes/CheatingInSchool.jpg",
      width: 528,
      height: 500,
      alt: "Cheating In School",
    },
    textareas: [
      {
        id: "Help:",
        top: 310,
        left: 250,
        width: 150,
        height: 100,
        text: "Scammed",
        size: 15,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "SpongeBob",
    background: {
      src: "/memes/SpongeBob.jpg",
      width: 725,
      height: 891,
      alt: "SpongeBob",
    },
    textareas: [
      {
        id: "List:",
        top: 110,
        left: 55,
        width: 220,
        height: 250,
        text: "list",
        size: 35,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Spongebob:",
        top: 370,
        left: 370,
        width: 350,
        height: 80,
        text: "spongebob",
        size: 50,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Tom And Jerry",
    background: {
      src: "/memes/TomJerry.jpg",
      width: 528,
      height: 500,
      alt: "Tom And Jerry",
    },
    textareas: [
      {
        id: "Script:",
        top: 0,
        left: 0,
        width: 528,
        height: 120,
        text: "Take all my ADAs",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Spider Man",
    background: {
      src: "/memes/SpiderMan.jpg",
      width: 528,
      height: 500,
      alt: "Spider Man",
    },
    textareas: [
      {
        id: "Spider man 1:",
        top: 10,
        left: 180,
        width: 200,
        height: 50,
        text: "BeepBoop",
        size: 40,
      },
      {
        id: "Spider man 2:",
        top: 50,
        left: 20,
        width: 200,
        height: 50,
        text: "Beep",
        size: 40,
      },
      {
        id: "Spider man 3:",
        top: 60,
        left: 320,
        width: 200,
        height: 50,
        text: "Boop",
        size: 40,
      },
    ],
  },
  {
    id: "Trade Offer",
    background: {
      src: "/memes/TradeOffer.jpg",
      width: 528,
      height: 500,
      alt: "Trade Offer",
    },
    textareas: [
      {
        id: "I Receive:",
        top: 150,
        left: 10,
        width: 200,
        height: 100,
        text: "Buy $BOT",
        size: 30,
      },
      {
        id: "You Receive:",
        top: 150,
        left: 280,
        width: 200,
        height: 100,
        text: "Became Rich",
        size: 30,
      },
    ],
  },
  {
    id: "Stick Man",
    background: {
      src: "/memes/WowHell.jpg",
      width: 528,
      height: 500,
      alt: "Stick Man",
    },
    textareas: [
      {
        id: "What happend:",
        top: 0,
        left: 0,
        width: 260,
        height: 200,
        text: "Made 10x on $BOT",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "What a hell:",
        top: 210,
        left: 0,
        width: 260,
        height: 200,
        text: "WTF",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Winnie The Pooh",
    background: {
      src: "/memes/WinnieThePooh.jpg",
      width: 528,
      height: 500,
      alt: "Winnie The Pooh",
    },
    textareas: [
      {
        id: "Street clothes:",
        top: 0,
        left: 230,
        width: 300,
        height: 200,
        text: "Buy $COCK",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Elegant dress:",
        top: 200,
        left: 230,
        width: 300,
        height: 200,
        text: "Buy $BOT",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "School Bus",
    background: {
      src: "/memes/SchoolBus.jpg",
      width: 528,
      height: 500,
      alt: "School Bus",
    },
    textareas: [
      {
        id: "School Bus:",
        top: 0,
        left: 0,
        width: 528,
        height: 100,
        text: "Min Swap $STABLE trader",
        size: 40,
      },
      {
        id: "Train:",
        top: 250,
        left: 0,
        width: 528,
        height: 200,
        text: "Min Swap $BOT trader",
        size: 40,
      },
    ],
  },
  {
    id: "Kid In Pool",
    background: {
      src: "/memes/KidInPool.jpg",
      width: 528,
      height: 500,
      alt: "Kid In Pool",
    },
    textareas: [
      {
        id: "Girl:",
        top: 25,
        left: 170,
        width: 200,
        height: 100,
        text: "$BOT",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Boy:",
        top: 180,
        left: 30,
        width: 200,
        height: 100,
        text: "$COCK",
        size: 40,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Skeleton:",
        top: 400,
        left: 180,
        width: 200,
        height: 100,
        text: "$SPICY",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Women VS Man",
    background: {
      src: "/memes/Men.jpg",
      width: 528,
      height: 500,
      alt: "Women VS Man",
    },
    textareas: [
      {
        id: "Man:",
        top: 260,
        left: 30,
        width: 285,
        height: 250,
        text: "I missed the $BOT Pre-Sale",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Wallet Ready",
    background: {
      src: "/memes/WalletReady.jpg",
      width: 528,
      height: 500,
      alt: "Wallet Ready",
    },
    textareas: [
      {
        id: "Unready:",
        top: 10,
        left: 275,
        width: 250,
        height: 200,
        text: "Buy Clay Mates NFT",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Ready:",
        top: 230,
        left: 275,
        width: 250,
        height: 200,
        text: "Buy Seeder NFT",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Pepe Life Style",
    background: {
      src: "/memes/PepeLife.jpg",
      width: 528,
      height: 500,
      alt: "Pepe Life Style",
    },
    textareas: [
      {
        id: "The reason:",
        top: 570,
        left: 90,
        width: 150,
        height: 200,
        text: "Say BeepBoop",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Hard Decision",
    background: {
      src: "/memes/HardDecision.jpg",
      width: 528,
      height: 500,
      alt: "Decision",
    },
    textareas: [
      {
        id: "Option 1:",
        top: 20,
        left: 70,
        width: 140,
        height: 200,
        text: "Buy $BOT on Pre-sale",
        size: 25,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Option 2:",
        top: -10,
        left: 240,
        width: 140,
        height: 200,
        text: "Buy Seeder NFT",
        size: 25,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Me:",
        top: 680,
        left: 0,
        width: 528,
        height: 100,
        text: "ME",
        size: 50,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
  {
    id: "Flex Tape",
    background: {
      src: "/memes/FlexTape.jpg",
      width: 528,
      height: 500,
      alt: "Flex Tape",
    },
    textareas: [
      {
        id: "Solution:",
        top: 10,
        left: 0,
        width: 200,
        height: 200,
        text: "$BOT",
        size: 50,
      },
      {
        id: "Problem:",
        top: 0,
        left: 250,
        width: 280,
        height: 150,
        text: "MemeCoin Season",
        size: 50,
      },
      {
        id: "Conclusion:",
        top: 300,
        left: 280,
        width: 200,
        height: 200,
        text: "June 19th",
        size: 50,
      },
    ],
  },
  {
    id: "No Way",
    background: {
      src: "/memes/NoWay.jpg",
      width: 528,
      height: 500,
      alt: "No Way",
    },
    textareas: [
      {
        id: "Option 1:",
        top: 0,
        left: 0,
        width: 285,
        height: 200,
        text: "Mint Seeder NFT for 150 ADAs",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
      {
        id: "Option 2:",
        top: 200,
        left: 0,
        width: 285,
        height: 200,
        text: "Buy from JPG for 2000 ADAs floor price",
        size: 30,
        color: "black",
        outlineColor: "white",
      },
    ],
  },
];

export default templates;
