export const botenomicsollection = [
  {
    left: "420 Billion",
    lclassNames: "font-hs font-semibold",
    span: "$",
    spanClass: "font-hs font-normal",
    right: "bot",
    rclassNames: " pb-[0.5em]",
  },
  {
    left: "PreSale",
    lclassNames: "",
    span: "",
    spanClass: "",
    right: "49%",
    rclassNames: "font-hs font-semibold",
  },
  {
    left: "Liquidity",
    lclassNames: "",
    span: "",
    spanClass: "",
    right: "42%",
    rclassNames: "font-hs font-semibold",
  },
  {
    left: "Community",
    lclassNames: "",
    span: "",
    spanClass: "",
    right: "5%",
    rclassNames: "font-hs font-semibold",
  },
  {
    left: "Reserve",
    lclassNames: "",
    span: "",
    spanClass: "",
    right: "3%",
    rclassNames: "font-hs font-semibold",
  },
  {
    left: "Team",
    lclassNames: "",
    span: "",
    spanClass: "",
    right: "1%",
    rclassNames: "font-hs font-semibold",
  },
];